import React, { useState } from 'react';
import { Menu, X, ExternalLink, MonitorSmartphone } from 'lucide-react';
import type { DesignConfig, EventDetails } from '../types';
import { CurrentAdminPanel } from './CurrentAdminPanel';

interface Props { eventDetails: EventDetails; onSaveEventDetails: (v: EventDetails) => void; designConfig: DesignConfig; onSaveDesignConfig: (v: DesignConfig) => void; onPreviewPdf?: () => void; }

export const CurrentAdminWorkspace: React.FC<Props> = ({ eventDetails, onSaveEventDetails, designConfig, onSaveDesignConfig, onPreviewPdf }) => {
  const [menuOpen, setMenuOpen] = useState(false);
  const [editorOpen, setEditorOpen] = useState(false);
  const publicUrl = `${window.location.pathname}?view=public`;
  return <main className="min-h-screen bg-[#0f0709] text-[#f7ead4]">
    <header className="flex h-16 items-center justify-between border-b border-[#c8a76a]/30 bg-[#1b0b0e] px-4 shadow-lg"><div className="flex items-center gap-3"><button onClick={() => setMenuOpen(true)} className="rounded-lg border border-[#c8a76a]/50 p-2 text-[#e4ca91]" aria-label="Open editor menu"><Menu /></button><div><p className="text-[10px] uppercase tracking-[.25em] text-[#d9b875]">Current version</p><h1 className="font-cinzel text-sm font-bold sm:text-lg">Wedding Invitation Studio</h1></div></div><a href={publicUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-lg border border-[#c8a76a]/50 px-3 py-2 text-xs text-[#e4ca91]">Open public page <ExternalLink size={14}/></a></header>
    <div className="grid min-h-[calc(100vh-4rem)] place-items-center bg-[#080405] p-4 sm:p-8"><section className="w-full max-w-6xl overflow-hidden rounded-2xl border border-[#c8a76a]/40 bg-[#211014] shadow-2xl"><div className="flex items-center gap-2 border-b border-[#c8a76a]/25 px-4 py-3 text-xs text-[#e4ca91]"><MonitorSmartphone size={16}/> Live invitation preview <span className="ml-auto text-[#f7ead4]/50">Edits appear here after Save</span></div><div className="grid gap-5 p-4 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="min-h-[650px] overflow-hidden rounded-xl border border-[#c8a76a]/30 bg-white"><iframe title="Live invitation preview" src={publicUrl} className="h-[760px] w-full border-0" /></div><aside className="hidden rounded-xl border border-[#c8a76a]/25 bg-[#1b0b0e] p-5 lg:block"><p className="text-xs uppercase tracking-widest text-[#d9b875]">Editor menu</p><h2 className="mt-2 font-cinzel text-lg text-[#e4ca91]">Open the side menu</h2><p className="mt-3 text-sm leading-6 text-[#f7ead4]/70">Use the menu button to edit the entrance, invitation content, events, appearance, sharing and PDF settings.</p><button onClick={() => setEditorOpen(true)} className="mt-5 w-full rounded-lg bg-[#d9b875] px-4 py-3 text-xs font-bold uppercase tracking-wider text-[#351017]">Start editing</button></aside></div></section></div>
    {menuOpen && <div className="fixed inset-0 z-[90] bg-black/55" onClick={() => setMenuOpen(false)}><aside className="h-full w-[min(88vw,380px)] overflow-y-auto border-r border-[#c8a76a]/50 bg-[#130709] p-5 shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-[#d9b875]">Studio menu</p><h2 className="font-cinzel text-lg text-[#e4ca91]">Edit current version</h2></div><button onClick={() => setMenuOpen(false)} className="rounded-lg p-2 text-[#e4ca91]"><X /></button></div><div className="mt-6 space-y-2"><button onClick={() => { setEditorOpen(true); setMenuOpen(false); }} className="w-full rounded-lg bg-[#c8a76a] px-4 py-3 text-left text-sm font-bold text-[#351017]">Invitation editor</button><a href={publicUrl} target="_blank" rel="noreferrer" className="block w-full rounded-lg border border-[#c8a76a]/40 px-4 py-3 text-sm">Open public invitation ↗</a></div></aside></div>}
    <CurrentAdminPanel isOpen={editorOpen} onClose={() => setEditorOpen(false)} eventDetails={eventDetails} onSaveEventDetails={onSaveEventDetails} designConfig={designConfig} onSaveDesignConfig={onSaveDesignConfig} onPreviewPdf={onPreviewPdf} />
  </main>;
};
