import React, { useState } from 'react';
import { Monitor, Smartphone, Menu, Save } from 'lucide-react';
import type { DesignConfig, EventDetails } from '../types';

interface Props { eventDetails: EventDetails; onSaveEventDetails: (v: EventDetails) => void; designConfig: DesignConfig; onSaveDesignConfig: (v: DesignConfig) => void; }
const input='mt-1 w-full rounded border border-[#c8a76a]/35 bg-[#16090b] px-2 py-2 text-xs text-[#f7ead4] outline-none focus:border-[#d9b875]';
const sections=[['entrance','Entrance'],['introduction','Introduction'],['events','Events'],['appearance','Appearance'],['sharing','Sharing'],['pdf','PDF']];
export const ThreePaneAdminWorkspace: React.FC<Props> = ({eventDetails,onSaveEventDetails,designConfig,onSaveDesignConfig})=>{
 const [section,setSection]=useState('entrance'); const [menu,setMenu]=useState(false); const [details,setDetails]=useState(eventDetails); const [design,setDesign]=useState(designConfig); const [dirty,setDirty]=useState(false);
 const setD=(v:Partial<EventDetails>)=>{setDetails(p=>({...p,...v}));setDirty(true)}; const setC=(v:Partial<DesignConfig>)=>{setDesign(p=>({...p,...v}));setDirty(true)}; const save=()=>{onSaveEventDetails(details);onSaveDesignConfig(design);setDirty(false)};
 const field=(label:string,value:string,onChange:(v:string)=>void)=><label className="block text-xs text-[#f7ead4]/80">{label}<input className={input} value={value} onChange={e=>onChange(e.target.value)}/></label>;
 return <main className="min-h-screen bg-[#080405] text-[#f7ead4]"><header className="flex h-14 items-center gap-3 border-b border-[#c8a76a]/30 bg-[#1b0b0e] px-3"><button onClick={()=>setMenu(!menu)} className="rounded border border-[#c8a76a]/50 p-2 lg:hidden"><Menu size={16}/></button><span className="font-cinzel text-sm text-[#e4ca91]">Wedding Invitation Studio</span><nav className="ml-3 flex min-w-0 flex-1 gap-1 overflow-x-auto">{sections.map(([id,label])=><button key={id} onClick={()=>setSection(id)} className={`whitespace-nowrap rounded px-3 py-2 text-[11px] font-semibold ${section===id?'bg-[#c8a76a] text-[#351017]':'text-[#f7ead4]/70 hover:bg-white/10'}`}>{label}</button>)}</nav><button onClick={save} className="flex shrink-0 items-center gap-1 rounded bg-[#c8a76a] px-3 py-2 text-[11px] font-bold text-[#351017]"><Save size={14}/>{dirty?'Save':'Saved'}</button></header><div className="grid min-h-[calc(100vh-3.5rem)] grid-cols-1 gap-3 p-3 lg:grid-cols-[270px_minmax(0,1fr)_300px]">
  <aside className={`${menu?'block':'hidden'} rounded-xl border border-[#c8a76a]/30 bg-[#130709] p-4 lg:block`}><p className="mb-4 text-[10px] uppercase tracking-[.2em] text-[#d9b875]">Edit {section}</p>{section==='entrance'&&<div className="space-y-3">{field('Left panel image',design.frontPanelLeftImage||'',v=>setC({frontPanelLeftImage:v}))}{field('Right panel image',design.frontPanelRightImage||'',v=>setC({frontPanelRightImage:v}))}<p className="text-[11px] text-[#f7ead4]/55">Opening seal and animation are fixed by the current entrance interaction.</p></div>}{section==='introduction'&&<div className="space-y-3">{field('Groom name',details.groomName,v=>setD({groomName:v}))}{field('Bride name',details.brideName,v=>setD({brideName:v}))}{field('Blessing heading',details.storyHeading,v=>setD({storyHeading:v}))}{field('Wedding date',details.weddingDate,v=>setD({weddingDate:v}))}</div>}{section==='events'&&<div className="space-y-3">{details.events.map((e,i)=><div key={e.id} className="rounded border border-[#c8a76a]/30 p-2">{field(`${i+1}. Event`,e.name,v=>setD({events:details.events.map(x=>x.id===e.id?{...x,name:v,title:v}:x)}))}{field('Venue',e.venueName,v=>setD({events:details.events.map(x=>x.id===e.id?{...x,venueName:v,venue:v}:x)}))}{field('Time',e.startTime,v=>setD({events:details.events.map(x=>x.id===e.id?{...x,startTime:v,time:v}:x)}))}</div>)}</div>}{section==='appearance'&&<div className="space-y-3">{field('Background image',design.backgroundImage,v=>setC({backgroundImage:v,backgroundType:'image'}))}{field('Background position',design.backgroundPosition,v=>setC({backgroundPosition:v as DesignConfig['backgroundPosition']}))}<div className="grid grid-cols-2 gap-2">{(['primaryColor','headingColor','textColor','accentColor'] as const).map(k=><label key={k} className="text-[11px]">{k}<input type="color" className="mt-1 h-8 w-full" value={design[k]} onChange={e=>setC({[k]:e.target.value})}/></label>)}</div></div>}{section==='sharing'&&<p className="text-xs leading-5 text-[#f7ead4]/65">The existing share link is generated from saved invitation data. RSVP responses currently use local browser storage; no shared backend is connected.</p>}{section==='pdf'&&<p className="text-xs leading-5 text-[#f7ead4]/65">PDF export uses the saved introduction, events, colors and typography. Use the PDF preview control after saving.</p>}</aside>
  <section className="min-h-[650px] overflow-hidden rounded-xl border border-[#c8a76a]/30 bg-white"><div className="flex items-center gap-2 border-b border-[#c8a76a]/20 bg-[#211014] px-3 py-2 text-xs text-[#e4ca91]"><Monitor size={15}/> Desktop live demo</div><iframe title="Desktop live invitation" src={`${window.location.pathname}?view=public`} className="h-[calc(100vh-7rem)] min-h-[650px] w-full border-0"/></section>
  <section className="mx-auto w-full max-w-[300px] overflow-hidden rounded-[28px] border-[8px] border-[#252126] bg-white shadow-xl"><div className="flex items-center gap-2 border-b border-[#c8a76a]/20 bg-[#211014] px-3 py-2 text-xs text-[#e4ca91]"><Smartphone size={15}/> iPhone live demo</div><iframe title="Mobile iPhone live invitation" src={`${window.location.pathname}?view=public`} className="h-[calc(100vh-8rem)] min-h-[620px] w-full border-0"/></section>
 </div></main>;
};
